# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wolfyre/OOP_indie_studio_2018

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wolfyre/OOP_indie_studio_2018

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wolfyre/OOP_indie_studio_2018/CMakeFiles /home/wolfyre/OOP_indie_studio_2018/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wolfyre/OOP_indie_studio_2018/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bomberman

# Build rule for target.
Bomberman: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Bomberman
.PHONY : Bomberman

# fast build rule for target.
Bomberman/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/build
.PHONY : Bomberman/fast

#=============================================================================
# Target rules for targets named MyIrrlicht

# Build rule for target.
MyIrrlicht: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyIrrlicht
.PHONY : MyIrrlicht

# fast build rule for target.
MyIrrlicht/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyIrrlicht.dir/build.make CMakeFiles/MyIrrlicht.dir/build
.PHONY : MyIrrlicht/fast

#=============================================================================
# Target rules for targets named studio

# Build rule for target.
studio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 studio
.PHONY : studio

# fast build rule for target.
studio/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/build
.PHONY : studio/fast

#=============================================================================
# Target rules for targets named Irrlicht

# Build rule for target.
Irrlicht: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Irrlicht
.PHONY : Irrlicht

# fast build rule for target.
Irrlicht/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Irrlicht.dir/build.make CMakeFiles/Irrlicht.dir/build
.PHONY : Irrlicht/fast

sources/Game/Game.o: sources/Game/Game.cpp.o

.PHONY : sources/Game/Game.o

# target to build an object file
sources/Game/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/Game.cpp.o
.PHONY : sources/Game/Game.cpp.o

sources/Game/Game.i: sources/Game/Game.cpp.i

.PHONY : sources/Game/Game.i

# target to preprocess a source file
sources/Game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/Game.cpp.i
.PHONY : sources/Game/Game.cpp.i

sources/Game/Game.s: sources/Game/Game.cpp.s

.PHONY : sources/Game/Game.s

# target to generate assembly for a file
sources/Game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/Game.cpp.s
.PHONY : sources/Game/Game.cpp.s

sources/Game/System/BombCountDownSystem.o: sources/Game/System/BombCountDownSystem.cpp.o

.PHONY : sources/Game/System/BombCountDownSystem.o

# target to build an object file
sources/Game/System/BombCountDownSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/BombCountDownSystem.cpp.o
.PHONY : sources/Game/System/BombCountDownSystem.cpp.o

sources/Game/System/BombCountDownSystem.i: sources/Game/System/BombCountDownSystem.cpp.i

.PHONY : sources/Game/System/BombCountDownSystem.i

# target to preprocess a source file
sources/Game/System/BombCountDownSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/BombCountDownSystem.cpp.i
.PHONY : sources/Game/System/BombCountDownSystem.cpp.i

sources/Game/System/BombCountDownSystem.s: sources/Game/System/BombCountDownSystem.cpp.s

.PHONY : sources/Game/System/BombCountDownSystem.s

# target to generate assembly for a file
sources/Game/System/BombCountDownSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/BombCountDownSystem.cpp.s
.PHONY : sources/Game/System/BombCountDownSystem.cpp.s

sources/Game/System/CollidingSystem.o: sources/Game/System/CollidingSystem.cpp.o

.PHONY : sources/Game/System/CollidingSystem.o

# target to build an object file
sources/Game/System/CollidingSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/CollidingSystem.cpp.o
.PHONY : sources/Game/System/CollidingSystem.cpp.o

sources/Game/System/CollidingSystem.i: sources/Game/System/CollidingSystem.cpp.i

.PHONY : sources/Game/System/CollidingSystem.i

# target to preprocess a source file
sources/Game/System/CollidingSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/CollidingSystem.cpp.i
.PHONY : sources/Game/System/CollidingSystem.cpp.i

sources/Game/System/CollidingSystem.s: sources/Game/System/CollidingSystem.cpp.s

.PHONY : sources/Game/System/CollidingSystem.s

# target to generate assembly for a file
sources/Game/System/CollidingSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/CollidingSystem.cpp.s
.PHONY : sources/Game/System/CollidingSystem.cpp.s

sources/Game/System/ExplosionCountDownSystem.o: sources/Game/System/ExplosionCountDownSystem.cpp.o

.PHONY : sources/Game/System/ExplosionCountDownSystem.o

# target to build an object file
sources/Game/System/ExplosionCountDownSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/ExplosionCountDownSystem.cpp.o
.PHONY : sources/Game/System/ExplosionCountDownSystem.cpp.o

sources/Game/System/ExplosionCountDownSystem.i: sources/Game/System/ExplosionCountDownSystem.cpp.i

.PHONY : sources/Game/System/ExplosionCountDownSystem.i

# target to preprocess a source file
sources/Game/System/ExplosionCountDownSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/ExplosionCountDownSystem.cpp.i
.PHONY : sources/Game/System/ExplosionCountDownSystem.cpp.i

sources/Game/System/ExplosionCountDownSystem.s: sources/Game/System/ExplosionCountDownSystem.cpp.s

.PHONY : sources/Game/System/ExplosionCountDownSystem.s

# target to generate assembly for a file
sources/Game/System/ExplosionCountDownSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/ExplosionCountDownSystem.cpp.s
.PHONY : sources/Game/System/ExplosionCountDownSystem.cpp.s

sources/Game/System/PoseBombSystem.o: sources/Game/System/PoseBombSystem.cpp.o

.PHONY : sources/Game/System/PoseBombSystem.o

# target to build an object file
sources/Game/System/PoseBombSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/PoseBombSystem.cpp.o
.PHONY : sources/Game/System/PoseBombSystem.cpp.o

sources/Game/System/PoseBombSystem.i: sources/Game/System/PoseBombSystem.cpp.i

.PHONY : sources/Game/System/PoseBombSystem.i

# target to preprocess a source file
sources/Game/System/PoseBombSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/PoseBombSystem.cpp.i
.PHONY : sources/Game/System/PoseBombSystem.cpp.i

sources/Game/System/PoseBombSystem.s: sources/Game/System/PoseBombSystem.cpp.s

.PHONY : sources/Game/System/PoseBombSystem.s

# target to generate assembly for a file
sources/Game/System/PoseBombSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/PoseBombSystem.cpp.s
.PHONY : sources/Game/System/PoseBombSystem.cpp.s

sources/Game/System/System_Ctor.o: sources/Game/System/System_Ctor.cpp.o

.PHONY : sources/Game/System/System_Ctor.o

# target to build an object file
sources/Game/System/System_Ctor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/System_Ctor.cpp.o
.PHONY : sources/Game/System/System_Ctor.cpp.o

sources/Game/System/System_Ctor.i: sources/Game/System/System_Ctor.cpp.i

.PHONY : sources/Game/System/System_Ctor.i

# target to preprocess a source file
sources/Game/System/System_Ctor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/System_Ctor.cpp.i
.PHONY : sources/Game/System/System_Ctor.cpp.i

sources/Game/System/System_Ctor.s: sources/Game/System/System_Ctor.cpp.s

.PHONY : sources/Game/System/System_Ctor.s

# target to generate assembly for a file
sources/Game/System/System_Ctor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/System/System_Ctor.cpp.s
.PHONY : sources/Game/System/System_Ctor.cpp.s

sources/Game/bot.o: sources/Game/bot.cpp.o

.PHONY : sources/Game/bot.o

# target to build an object file
sources/Game/bot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/bot.cpp.o
.PHONY : sources/Game/bot.cpp.o

sources/Game/bot.i: sources/Game/bot.cpp.i

.PHONY : sources/Game/bot.i

# target to preprocess a source file
sources/Game/bot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/bot.cpp.i
.PHONY : sources/Game/bot.cpp.i

sources/Game/bot.s: sources/Game/bot.cpp.s

.PHONY : sources/Game/bot.s

# target to generate assembly for a file
sources/Game/bot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/bot.cpp.s
.PHONY : sources/Game/bot.cpp.s

sources/Game/botDump.o: sources/Game/botDump.cpp.o

.PHONY : sources/Game/botDump.o

# target to build an object file
sources/Game/botDump.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/botDump.cpp.o
.PHONY : sources/Game/botDump.cpp.o

sources/Game/botDump.i: sources/Game/botDump.cpp.i

.PHONY : sources/Game/botDump.i

# target to preprocess a source file
sources/Game/botDump.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/botDump.cpp.i
.PHONY : sources/Game/botDump.cpp.i

sources/Game/botDump.s: sources/Game/botDump.cpp.s

.PHONY : sources/Game/botDump.s

# target to generate assembly for a file
sources/Game/botDump.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/botDump.cpp.s
.PHONY : sources/Game/botDump.cpp.s

sources/Game/botGetters.o: sources/Game/botGetters.cpp.o

.PHONY : sources/Game/botGetters.o

# target to build an object file
sources/Game/botGetters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/botGetters.cpp.o
.PHONY : sources/Game/botGetters.cpp.o

sources/Game/botGetters.i: sources/Game/botGetters.cpp.i

.PHONY : sources/Game/botGetters.i

# target to preprocess a source file
sources/Game/botGetters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/botGetters.cpp.i
.PHONY : sources/Game/botGetters.cpp.i

sources/Game/botGetters.s: sources/Game/botGetters.cpp.s

.PHONY : sources/Game/botGetters.s

# target to generate assembly for a file
sources/Game/botGetters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/botGetters.cpp.s
.PHONY : sources/Game/botGetters.cpp.s

sources/Game/botMoves.o: sources/Game/botMoves.cpp.o

.PHONY : sources/Game/botMoves.o

# target to build an object file
sources/Game/botMoves.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/botMoves.cpp.o
.PHONY : sources/Game/botMoves.cpp.o

sources/Game/botMoves.i: sources/Game/botMoves.cpp.i

.PHONY : sources/Game/botMoves.i

# target to preprocess a source file
sources/Game/botMoves.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/botMoves.cpp.i
.PHONY : sources/Game/botMoves.cpp.i

sources/Game/botMoves.s: sources/Game/botMoves.cpp.s

.PHONY : sources/Game/botMoves.s

# target to generate assembly for a file
sources/Game/botMoves.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/botMoves.cpp.s
.PHONY : sources/Game/botMoves.cpp.s

sources/Game/placeDump.o: sources/Game/placeDump.cpp.o

.PHONY : sources/Game/placeDump.o

# target to build an object file
sources/Game/placeDump.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placeDump.cpp.o
.PHONY : sources/Game/placeDump.cpp.o

sources/Game/placeDump.i: sources/Game/placeDump.cpp.i

.PHONY : sources/Game/placeDump.i

# target to preprocess a source file
sources/Game/placeDump.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placeDump.cpp.i
.PHONY : sources/Game/placeDump.cpp.i

sources/Game/placeDump.s: sources/Game/placeDump.cpp.s

.PHONY : sources/Game/placeDump.s

# target to generate assembly for a file
sources/Game/placeDump.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placeDump.cpp.s
.PHONY : sources/Game/placeDump.cpp.s

sources/Game/placeFinding.o: sources/Game/placeFinding.cpp.o

.PHONY : sources/Game/placeFinding.o

# target to build an object file
sources/Game/placeFinding.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placeFinding.cpp.o
.PHONY : sources/Game/placeFinding.cpp.o

sources/Game/placeFinding.i: sources/Game/placeFinding.cpp.i

.PHONY : sources/Game/placeFinding.i

# target to preprocess a source file
sources/Game/placeFinding.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placeFinding.cpp.i
.PHONY : sources/Game/placeFinding.cpp.i

sources/Game/placeFinding.s: sources/Game/placeFinding.cpp.s

.PHONY : sources/Game/placeFinding.s

# target to generate assembly for a file
sources/Game/placeFinding.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placeFinding.cpp.s
.PHONY : sources/Game/placeFinding.cpp.s

sources/Game/placePlayer.o: sources/Game/placePlayer.cpp.o

.PHONY : sources/Game/placePlayer.o

# target to build an object file
sources/Game/placePlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placePlayer.cpp.o
.PHONY : sources/Game/placePlayer.cpp.o

sources/Game/placePlayer.i: sources/Game/placePlayer.cpp.i

.PHONY : sources/Game/placePlayer.i

# target to preprocess a source file
sources/Game/placePlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placePlayer.cpp.i
.PHONY : sources/Game/placePlayer.cpp.i

sources/Game/placePlayer.s: sources/Game/placePlayer.cpp.s

.PHONY : sources/Game/placePlayer.s

# target to generate assembly for a file
sources/Game/placePlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placePlayer.cpp.s
.PHONY : sources/Game/placePlayer.cpp.s

sources/Game/placement.o: sources/Game/placement.cpp.o

.PHONY : sources/Game/placement.o

# target to build an object file
sources/Game/placement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placement.cpp.o
.PHONY : sources/Game/placement.cpp.o

sources/Game/placement.i: sources/Game/placement.cpp.i

.PHONY : sources/Game/placement.i

# target to preprocess a source file
sources/Game/placement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placement.cpp.i
.PHONY : sources/Game/placement.cpp.i

sources/Game/placement.s: sources/Game/placement.cpp.s

.PHONY : sources/Game/placement.s

# target to generate assembly for a file
sources/Game/placement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/sources/Game/placement.cpp.s
.PHONY : sources/Game/placement.cpp.s

sources/Graph/Graph.o: sources/Graph/Graph.cpp.o

.PHONY : sources/Graph/Graph.o

# target to build an object file
sources/Graph/Graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyIrrlicht.dir/build.make CMakeFiles/MyIrrlicht.dir/sources/Graph/Graph.cpp.o
.PHONY : sources/Graph/Graph.cpp.o

sources/Graph/Graph.i: sources/Graph/Graph.cpp.i

.PHONY : sources/Graph/Graph.i

# target to preprocess a source file
sources/Graph/Graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyIrrlicht.dir/build.make CMakeFiles/MyIrrlicht.dir/sources/Graph/Graph.cpp.i
.PHONY : sources/Graph/Graph.cpp.i

sources/Graph/Graph.s: sources/Graph/Graph.cpp.s

.PHONY : sources/Graph/Graph.s

# target to generate assembly for a file
sources/Graph/Graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyIrrlicht.dir/build.make CMakeFiles/MyIrrlicht.dir/sources/Graph/Graph.cpp.s
.PHONY : sources/Graph/Graph.cpp.s

sources/core.o: sources/core.cpp.o

.PHONY : sources/core.o

# target to build an object file
sources/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/core.cpp.o
.PHONY : sources/core.cpp.o

sources/core.i: sources/core.cpp.i

.PHONY : sources/core.i

# target to preprocess a source file
sources/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/core.cpp.i
.PHONY : sources/core.cpp.i

sources/core.s: sources/core.cpp.s

.PHONY : sources/core.s

# target to generate assembly for a file
sources/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/core.cpp.s
.PHONY : sources/core.cpp.s

sources/main.o: sources/main.cpp.o

.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i

.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s

.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

sources/main_menu.o: sources/main_menu.cpp.o

.PHONY : sources/main_menu.o

# target to build an object file
sources/main_menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/main_menu.cpp.o
.PHONY : sources/main_menu.cpp.o

sources/main_menu.i: sources/main_menu.cpp.i

.PHONY : sources/main_menu.i

# target to preprocess a source file
sources/main_menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/main_menu.cpp.i
.PHONY : sources/main_menu.cpp.i

sources/main_menu.s: sources/main_menu.cpp.s

.PHONY : sources/main_menu.s

# target to generate assembly for a file
sources/main_menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/main_menu.cpp.s
.PHONY : sources/main_menu.cpp.s

sources/menu_continue.o: sources/menu_continue.cpp.o

.PHONY : sources/menu_continue.o

# target to build an object file
sources/menu_continue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/menu_continue.cpp.o
.PHONY : sources/menu_continue.cpp.o

sources/menu_continue.i: sources/menu_continue.cpp.i

.PHONY : sources/menu_continue.i

# target to preprocess a source file
sources/menu_continue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/menu_continue.cpp.i
.PHONY : sources/menu_continue.cpp.i

sources/menu_continue.s: sources/menu_continue.cpp.s

.PHONY : sources/menu_continue.s

# target to generate assembly for a file
sources/menu_continue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/menu_continue.cpp.s
.PHONY : sources/menu_continue.cpp.s

sources/menu_local.o: sources/menu_local.cpp.o

.PHONY : sources/menu_local.o

# target to build an object file
sources/menu_local.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/menu_local.cpp.o
.PHONY : sources/menu_local.cpp.o

sources/menu_local.i: sources/menu_local.cpp.i

.PHONY : sources/menu_local.i

# target to preprocess a source file
sources/menu_local.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/menu_local.cpp.i
.PHONY : sources/menu_local.cpp.i

sources/menu_local.s: sources/menu_local.cpp.s

.PHONY : sources/menu_local.s

# target to generate assembly for a file
sources/menu_local.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/menu_local.cpp.s
.PHONY : sources/menu_local.cpp.s

sources/menu_multi.o: sources/menu_multi.cpp.o

.PHONY : sources/menu_multi.o

# target to build an object file
sources/menu_multi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/menu_multi.cpp.o
.PHONY : sources/menu_multi.cpp.o

sources/menu_multi.i: sources/menu_multi.cpp.i

.PHONY : sources/menu_multi.i

# target to preprocess a source file
sources/menu_multi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/menu_multi.cpp.i
.PHONY : sources/menu_multi.cpp.i

sources/menu_multi.s: sources/menu_multi.cpp.s

.PHONY : sources/menu_multi.s

# target to generate assembly for a file
sources/menu_multi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/menu_multi.cpp.s
.PHONY : sources/menu_multi.cpp.s

sources/parsers.o: sources/parsers.cpp.o

.PHONY : sources/parsers.o

# target to build an object file
sources/parsers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/parsers.cpp.o
.PHONY : sources/parsers.cpp.o

sources/parsers.i: sources/parsers.cpp.i

.PHONY : sources/parsers.i

# target to preprocess a source file
sources/parsers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/parsers.cpp.i
.PHONY : sources/parsers.cpp.i

sources/parsers.s: sources/parsers.cpp.s

.PHONY : sources/parsers.s

# target to generate assembly for a file
sources/parsers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/studio.dir/build.make CMakeFiles/studio.dir/sources/parsers.cpp.s
.PHONY : sources/parsers.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Irrlicht"
	@echo "... Bomberman"
	@echo "... MyIrrlicht"
	@echo "... studio"
	@echo "... sources/Game/Game.o"
	@echo "... sources/Game/Game.i"
	@echo "... sources/Game/Game.s"
	@echo "... sources/Game/System/BombCountDownSystem.o"
	@echo "... sources/Game/System/BombCountDownSystem.i"
	@echo "... sources/Game/System/BombCountDownSystem.s"
	@echo "... sources/Game/System/CollidingSystem.o"
	@echo "... sources/Game/System/CollidingSystem.i"
	@echo "... sources/Game/System/CollidingSystem.s"
	@echo "... sources/Game/System/ExplosionCountDownSystem.o"
	@echo "... sources/Game/System/ExplosionCountDownSystem.i"
	@echo "... sources/Game/System/ExplosionCountDownSystem.s"
	@echo "... sources/Game/System/PoseBombSystem.o"
	@echo "... sources/Game/System/PoseBombSystem.i"
	@echo "... sources/Game/System/PoseBombSystem.s"
	@echo "... sources/Game/System/System_Ctor.o"
	@echo "... sources/Game/System/System_Ctor.i"
	@echo "... sources/Game/System/System_Ctor.s"
	@echo "... sources/Game/bot.o"
	@echo "... sources/Game/bot.i"
	@echo "... sources/Game/bot.s"
	@echo "... sources/Game/botDump.o"
	@echo "... sources/Game/botDump.i"
	@echo "... sources/Game/botDump.s"
	@echo "... sources/Game/botGetters.o"
	@echo "... sources/Game/botGetters.i"
	@echo "... sources/Game/botGetters.s"
	@echo "... sources/Game/botMoves.o"
	@echo "... sources/Game/botMoves.i"
	@echo "... sources/Game/botMoves.s"
	@echo "... sources/Game/placeDump.o"
	@echo "... sources/Game/placeDump.i"
	@echo "... sources/Game/placeDump.s"
	@echo "... sources/Game/placeFinding.o"
	@echo "... sources/Game/placeFinding.i"
	@echo "... sources/Game/placeFinding.s"
	@echo "... sources/Game/placePlayer.o"
	@echo "... sources/Game/placePlayer.i"
	@echo "... sources/Game/placePlayer.s"
	@echo "... sources/Game/placement.o"
	@echo "... sources/Game/placement.i"
	@echo "... sources/Game/placement.s"
	@echo "... sources/Graph/Graph.o"
	@echo "... sources/Graph/Graph.i"
	@echo "... sources/Graph/Graph.s"
	@echo "... sources/core.o"
	@echo "... sources/core.i"
	@echo "... sources/core.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
	@echo "... sources/main_menu.o"
	@echo "... sources/main_menu.i"
	@echo "... sources/main_menu.s"
	@echo "... sources/menu_continue.o"
	@echo "... sources/menu_continue.i"
	@echo "... sources/menu_continue.s"
	@echo "... sources/menu_local.o"
	@echo "... sources/menu_local.i"
	@echo "... sources/menu_local.s"
	@echo "... sources/menu_multi.o"
	@echo "... sources/menu_multi.i"
	@echo "... sources/menu_multi.s"
	@echo "... sources/parsers.o"
	@echo "... sources/parsers.i"
	@echo "... sources/parsers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

